# Site settings
author: Kyle Stough
title: Kyle.Flatiron/Blog
header-img: img/home-bg.png
email: kstough00@gmail.com
copyright_name: Kyle Stough
description: > # this means to ignore newlines until "baseurl:"
  This is Kyle's Blog!
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  kstough00

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
